; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200


[env:native]
platform = native
test_framework = unity

build_src_filter =
    +<control/Converter.cpp>
    +<control/PIDController.cpp>

test_build_src = yes

[env:native_axis]
platform = native
test_framework = unity

build_src_filter =
    +<control/PIDController.cpp>
    +<control/AxisController.cpp>

test_build_src = yes
test_filter = test_axis_controller

build_flags =
    -I test/test_axis_controller/stubs

[env:native_xy]
platform = native
test_framework = unity

build_src_filter =
    +<control/Converter.cpp>
    +<control/PIDController.cpp>
    +<control/AxisController.cpp>
    +<control/XYCoordinator.cpp>

test_build_src = yes
test_filter = test_xy_coordinator

build_flags =
    -I test/test_xy_coordinator/stubs